version: '3'

services:
  #   tty: true
  # nest:
  #   env_file:
  #     - ./config/development.env
  #   image: node:${NODE_VERSION}
  #   working_dir: /home/node/app
  #   command: npm config set registry https://registry.npm.taobao.org
  #   command: npm run start:dev
  #   volumes:
  #     - ./:/home/node/app
  #   ports:
  #     - ${APP_PORT}:3000

  mysql:
    env_file:
      - ./config/development.env
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      # MYSQL_ROOT_PASSWORD: MYSQL_PASSWORD
      MYSQL_DATABASE: nest
      MYSQL_USER: root
      MYSQL_PASSWORD: abc123456

  redis:
    image: redis:4
    ports:
      - 6379:6379
    # volumes:
    #   # 目录映射
    #   - "${REDIS_DIR}/conf:/usr/local/etc/redis"
    #   - "${REDIS_DIR}/data:/data"
    command: redis-server

  nginx:
    restart: always
    image: nginx:1.11.6-alpine
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - ./log:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
