version: '3'

services:
  #   tty: true
  # nest:
  #   env_file:
  #     - ./config/development.env
  #   image: node:${NODE_VERSION}
  #   working_dir: /home/node/app
  #   command: npm config set registry https://registry.npm.taobao.org
  #   command: npm run start:dev
  #   volumes:
  #     - ./:/home/node/app
  #   ports:
  #     - ${APP_PORT}:3000

  # commands:
  #   image: node:${NODE_VERSION}
  #   working_dir: /home/app
  #   command: npm config set registry https://registry.npm.taobao.org
  #   command: npm run build
  #   env_file: .env
  #   environment:
  #       TZ : 'Asia/Shanghai' # 东八区
  #   volumes:
  #     - ./commands:/home/app
  #   depends_on:
  #     - mysql

  mysql:
    env_file: .env
    image: mysql:${MYSQL_VERSION}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - ${MYSQL_PORT}:3306

  redis:
    env_file: .env
    image: redis:${REDIS_DB}
    ports:
      - ${REDIS_PORT}:6379
    # volumes:
    #   # 目录映射
    #   - "${REDIS_DIR}/conf:/usr/local/etc/redis"
    #   - "${REDIS_DIR}/data:/data"
    command: redis-server

  nginx:
    restart: always
    # 指定目录下的dockerfile
    build: ./nginx
    environment:
      TZ: 'Asia/Shanghai' # 东八区
    ports:
      - 9090:80
    volumes:
      - ./log:/var/log/nginx
      - ./nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/sh:/home
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
